// Russian translations of the original English in-game texts (originals are kept as fallback).
export const RU: Record<string, string> = {
  "There are hairs scattered here.": 'Здесь разбросаны волосы.',
  "A hemostatic capsule\nis on the floor.": 'На полу лежит\nкровоостанавливающая капсула.',
  "It's empty.": 'Она пуста.',
  "Old prisoner's uniforms\nare piled up here.": 'Здесь свалены старые\nтюремные робы.',
  "He seems to be in great pain.": 'Похоже, ему очень больно.',
  "I shouldn't talk to him.": 'Не стоит с ним заговаривать.',
  "If I were equipped with a \nlighter, I could see outside...": 'Будь у меня зажигалка,\nя бы разглядела, что снаружи...',
  "His eyes are closed.": 'Его глаза закрыты.',
  "He's bleeding.\nI'll need hemostatic medicine...": 'У него кровотечение.\nНужно кровоостанавливающее...',
  "A disorganized pile of\nvarious documents.": 'Беспорядочная груда\nразных документов.',
  "This area is completely\nvoid of light.": 'Здесь совершенно\nнет света.',
  "I don't think I can\ntreat his wound properly.": 'Вряд ли я смогу\nкак следует обработать его рану.',
  "It's too dark to\nmake out anything.": 'Слишком темно,\nничего не разглядеть.',
  "It's a list of prisoners.\nMy name is at the end.": 'Это список заключённых.\nМоё имя — в самом конце.',
  "The escort's name is at\nthe end of the document.": 'Имя конвоира указано\nв конце документа.',
  "An old typewriter.": 'Старая пишущая машинка.',
  "I could save my progress\nif I had an ink ribbon.": 'Я могла бы сохраниться,\nбудь у меня красящая лента.',
  "You can save your\nprogress with this.": 'С её помощью можно\nсохранить прогресс.',
  "A truck used for transport.": 'Грузовик для перевозок.',
  "Oil is leaking from the\ncrashed wreck.": 'Из разбитой машины\nвытекает масло.',
  "A dead body and a\nbriefcase can be seen inside.": 'Внутри видны труп\nи кейс.',
  "It looks like it\ncrashed into the wall.": 'Похоже, он врезался\nв стену.',
  "He is not breathing.": 'Он не дышит.',
  "This is the central gate\nof the prison.": 'Это центральные ворота\nтюрьмы.',
  "It's locked.": 'Заперто.',
  "A hawk's picture is\ncarved into the hollow.": 'В углублении вырезано\nизображение ястреба.',
  "It's been completely\nnailed down.": 'Всё наглухо\nзаколочено.',
  "It's impossible to open it.": 'Открыть невозможно.',
  "Apparently, a dust box.": 'Похоже, мусорный ящик.',
  "Abandoned materials\nare piled up here.": "Здесь свалены\nброшенные материалы.",
  "Nothing useful.": "Ничего полезного.",
  "It's been locked with a padlock.": "Заперто на висячий замок.",
  "It's been locked from\nthe other side with a padlock.": "Заперто на висячий замок\nс другой стороны.",
  "It can't be opened\nfrom this side.": "С этой стороны\nне открыть.",
  "There is a big hole in\nthe wire netting...": "В проволочной сетке\nбольшая дыра...",
  "There is a bloodstain\nunder the eaves.": "Под навесом\nпятно крови.",
  "You no longer need to use\nthis key.": "Этот ключ больше\nне понадобится.",
  "It seems that someone\ndidn't finish their soup.": "Похоже, кто-то\nне доел свой суп.",
  "It's still a bit warm...": "Он ещё немного тёплый...",
  "Nothing useful here.": "Здесь ничего полезного.",
  "Shabby magazines are\npiled up here.": "Здесь свалены\nпотрёпанные журналы.",
  "This toilet has some\nrather disgusting stains.": "На этом унитазе\nотвратительные пятна.",
  "A horrible smell lingers...": "Стоит ужасный запах...",
  "Half-eaten food items are\nscattered in this area.": "Здесь разбросаны\nнедоеденные продукты.",
  "Take the prison map?": "Взять карту тюрьмы?",
  "You've taken the prison map.": "Вы взяли карту тюрьмы.",
  "There is an indentation\non the indigo blue plate.": "На тёмно-синей пластине\nесть углубление.",
  "It appears to be locked.": "Похоже, заперто.",
  "I must release the lock first.": "Сначала нужно\nснять блокировку.",
  "This switch controls\nthe outdoor shutters.": "Этот переключатель управляет\nнаружными ставнями.",
  "Push the switch?": "Нажать переключатель?",
  "A guillotine, covered in blood.": "Гильотина, вся в крови.",
  "It seems that there is\nsome fresh blood on it.": "Похоже, на ней\nсвежая кровь.",
  "Something seems to have\nbeen tied up here...": "Похоже, здесь кого-то\nдержали связанным...",
  "Fresh blood is stuck\nto the wall...": "На стене\nсвежая кровь...",
  "A person might have been\ntied to the pillar...": "Возможно, к столбу\nбыл привязан человек...",
  "It's completely nailed down.": "Всё наглухо заколочено.",
  "The outdoor shutter is locked.": "Наружная ставня заперта.",
  "I must release the lock.": "Нужно снять блокировку.",
  "The outdoor shutter\nis already open.": "Наружная ставня\nуже открыта.",
  "The lock has already\nbeen released.": "Блокировка\nуже снята.",
  "Perhaps I can open it\nwith the switch on the left...": "Может, её можно открыть\nпереключателем слева...",
  "An outdoor shutter.": "Наружная ставня.",
};
export const ITEM_RU: Record<string, string> = {
  'Combat Knife': 'Боевой нож', 'Map': 'Карта', 'Extinguisher': 'Огнетушитель', 'Eagle Plate': 'Пластина с орлом', 'Handgun Bullets': 'Патроны для пистолета', 'Green Herb': 'Зелёная трава',
  'Ink Ribbon': 'Красящая лента', 'Board Clip': 'Планшет с бумагами', 'Hemostatic': 'Кровоостанавливающее',
  'Lighter': 'Зажигалка', 'Briefcase': 'Кейс', 'Hawk Emblem': 'Эмблема ястреба', 'Sp. Alloy Emblem': 'Эмблема из спецсплава', 'Memo': 'Записка', 'Lockpick': 'Отмычка', 'Handgun': 'Пистолет', 'F. Aid Spray': 'Аптечка-спрей',
};
export let LANG: 'ru' | 'en' = (localStorage.getItem('cvx.lang') as any) || 'ru';
export function setLang(l: 'ru' | 'en') { LANG = l; localStorage.setItem('cvx.lang', l); }
/** Split original message into pages (form-feed separated) and translate each page. */
export function pages(msg: string): string[] {
  const raw = msg.replace(/<0>|<1>/g, '').replace(/\n\s*\{4:39\}es\s+\{4:2e\}o/g, '').replace(/\{0d\}/g, '-').split('\f').map((s) => s.replace(/^\n+/, '').replace(/\{[0-9a-f]+:[0-9a-f]+\}/g, '').trimEnd()).filter((s) => s.trim().length);
  if (LANG === 'en') return raw;
  return raw.map((p) => RU[p] ?? RU[p.trim()] ?? p);
}
export function itemName(en: string) { return LANG === 'ru' ? (ITEM_RU[en] ?? en) : en; }
const ru = () => LANG === 'ru';
export const UI = {
  take: () => (ru() ? 'Взять' : 'Take'),
  takeQ: (n: string) => (ru() ? `Взять: ${n}?` : `Will you take the ${n}?`),
  yes: () => (ru() ? 'Да' : 'Yes'), no: () => (ru() ? 'Нет' : 'No'),
  got: (n: string) => (ru() ? `Получено: ${n}.` : `Picked up the ${n}.`),
  full: () => (ru() ? 'Нет места в инвентаре.' : 'You cannot carry any more items.'),
  saveQ: () => (ru() ? 'Сохранить игру? (будет использована красящая лента)' : 'Use an ink ribbon to save?'),
  saved: () => (ru() ? 'Игра сохранена.' : 'Game saved.'),
  locked: () => (ru() ? 'Эта часть игры\nпока не перенесена.' : 'This area is\nnot ported yet.'),
  camFixed: () => (ru() ? 'Камера: фиксированная' : 'Camera: fixed'),
  camBehind: () => (ru() ? 'Камера: от плеча (мышь — обзор)' : 'Camera: over the shoulder (mouse to look)'),
  // lighter-lit variants of the dark-area messages
  litOutside: () => (ru() ? 'При свете зажигалки видно:\nза решёткой лишь пустой\nтёмный коридор...' : 'By the lighter\'s flame I can see\nonly an empty, dark\ncorridor outside...'),
  litDark: () => (ru() ? 'Зажигалка освещает угол.\nЗдесь ничего нет.' : 'The lighter lights up the corner.\nThere is nothing here.'),
  litWound: () => (ru() ? 'Даже при свете зажигалки\nя вряд ли смогу как следует\nобработать его рану.' : "Even with the lighter I don't\nthink I can treat\nhis wound properly."),
};
