import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/usr/local/bin/chromium', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = []; page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message));
await page.addInitScript(() => localStorage.setItem('cv.settings', JSON.stringify({ quality: 'low', sensitivity: 1, aimAssist: 0.5, volume: 0, invertY: false })));
await page.goto('file:///data/cv-remake/dist/play.html'); await page.waitForTimeout(1500);
await page.click('text=НОВАЯ ИГРА'); await page.waitForTimeout(5000);
await page.evaluate(() => { const w = window.__game.world; w.inventory.add('gp_a', 1); w.inventory.add('gp_a', 1); w.player.hp = 30; });
await page.keyboard.press('Tab'); await page.waitForTimeout(1000);
const item = (name, i = 0) => page.locator('.inv-item', { has: page.locator('.nm', { hasText: name }) }).nth(i);
await item('Gunpowder A', 0).click(); await page.click('button:has-text("Совместить")');
await item('Gunpowder A', 1).click(); await page.waitForTimeout(500);
console.log('desc:', await page.$eval('.desc', e => e.textContent));
await item('Green Herb').click(); await page.click('button:has-text("Использовать")'); await page.waitForTimeout(500);
console.log(JSON.stringify(await page.evaluate(() => ({ hp: window.__game.world.player.hp, items: window.__game.world.inventory.items.map(i => i.defId + 'x' + i.qty) }))));
await page.screenshot({ path: 'shots/inv_after.png' });
console.log(errors.join('\n')); await browser.close();
