import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/usr/local/bin/chromium', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 640, height: 360 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.addInitScript(() => localStorage.setItem('cv.settings', JSON.stringify({ quality: 'low', volume: 0 })));
await page.goto('file:///data/cv-remake/dist/play.html');
await page.waitForTimeout(800);
await page.click('text=НОВАЯ ИГРА');
await page.waitForTimeout(4000);
await page.mouse.move(320, 180);
await page.mouse.down({ button: 'right' });
await page.waitForTimeout(3000);
console.log(await page.evaluate(() => {
  const w = window.__game.world; const m = w.player.model; const r = m.rig;
  const sk = m.root.children.find(c => c.isSkinnedMesh);
  const hand = r.rHand.getWorldPosition(new (w.player.pos.constructor)());
  return JSON.stringify({ aiming: w.player.aiming, aimBlend: m.aimBlend, rUx: r.rUpperArm.rotation.x, lUx: r.lUpperArm.rotation.x, hand: hand.toArray(), pos: w.player.pos.toArray(), inSkel: sk.skeleton.bones.includes(r.rUpperArm), nb: sk.skeleton.bones.length, t: w.time });
}));
await page.screenshot({ path: 'shots/pose.png' });
await browser.close();
